# ATS slugs and tenant IDs are best-effort guesses and may need updating.
# Greenhouse: verify at https://boards.greenhouse.io/<slug>
# Lever:      verify at https://jobs.lever.co/<slug>
# Workday:    verify tenant/board/subdomain from the company's careers URL
# Ashby:      verify at https://jobs.ashbyhq.com/<slug>

COMPANIES: dict[str, list[dict]] = {
    "Strong": [
        {"name": "Databricks",  "ats": "greenhouse", "slug": "databricks"},
        {"name": "GitHub",      "ats": "greenhouse", "slug": "github"},
        {"name": "Wiz",         "ats": "greenhouse", "slug": "wiz"},
        {"name": "Samsara",     "ats": "greenhouse", "slug": "samsara"},
        {"name": "Stripe",      "ats": "greenhouse", "slug": "stripe"},
        {"name": "Ramp",        "ats": "greenhouse", "slug": "ramp"},
        {"name": "Mercury",     "ats": "greenhouse", "slug": "mercury"},
        {"name": "Hightouch",   "ats": "greenhouse", "slug": "hightouch"},
        {"name": "1Password",   "ats": "greenhouse", "slug": "1password"},
        {
            "name": "Genesys",
            "ats": "workday",
            "tenant": "genesys",
            "board": "Genesys",
            "wd_subdomain": "wd1",
        },
        {
            "name": "Adobe",
            "ats": "workday",
            "tenant": "adobe",
            "board": "external_experienced",
            "wd_subdomain": "wd5",
        },
    ],
    "Moderate": [
        {"name": "Dandy",       "ats": "greenhouse", "slug": "dandy"},
        {"name": "Openly",      "ats": "greenhouse", "slug": "openly"},
        {"name": "Ashby",       "ats": "ashby",      "slug": "ashby"},
        {"name": "Benepass",    "ats": "greenhouse", "slug": "benepass"},
        {"name": "PolyAI",      "ats": "greenhouse", "slug": "polyai"},
        {"name": "Hungryroot",  "ats": "greenhouse", "slug": "hungryroot"},
        {"name": "Attentive",   "ats": "greenhouse", "slug": "attentivemobile"},
        {"name": "LiveRamp",    "ats": "greenhouse", "slug": "liveramp"},
        {"name": "Pinterest",   "ats": "greenhouse", "slug": "pinterest"},
        {"name": "Instacart",   "ats": "greenhouse", "slug": "instacart"},
        {"name": "Discord",     "ats": "greenhouse", "slug": "discord"},
        {"name": "Acorns",      "ats": "greenhouse", "slug": "acorns"},
        {"name": "Fetch",       "ats": "greenhouse", "slug": "fetch-rewards"},
        {"name": "American Journalism Project", "ats": "greenhouse", "slug": "theajp"},
        {"name": "Beehiiv",     "ats": "greenhouse", "slug": "beehiiv"},
        {"name": "Whatnot",     "ats": "greenhouse", "slug": "whatnot"},
        {"name": "Webflow",     "ats": "greenhouse", "slug": "webflow"},
        {"name": "Aha!",        "ats": "greenhouse", "slug": "aha"},
        {"name": "Fractal",     "ats": "greenhouse", "slug": "fractal-analytics"},
        {"name": "Pacvue",      "ats": "greenhouse", "slug": "pacvue"},
        {"name": "Halcyon",     "ats": "greenhouse", "slug": "halcyon"},
        {"name": "Kitman Labs", "ats": "greenhouse", "slug": "kitmanlabs"},
        {"name": "Viral Nation","ats": "greenhouse", "slug": "viralnation"},
        {"name": "Payscale",    "ats": "greenhouse", "slug": "payscale"},
        {"name": "Duetto",      "ats": "greenhouse", "slug": "duetto"},
        {"name": "DEPT",        "ats": "greenhouse", "slug": "dept"},
        {"name": "Motive",      "ats": "greenhouse", "slug": "gomotive"},
        {
            "name": "Akamai",
            "ats": "workday",
            "tenant": "akamai",
            "board": "External",
            "wd_subdomain": "wd5",
        },
        {
            "name": "Cotiviti",
            "ats": "workday",
            "tenant": "cotiviti",
            "board": "External",
            "wd_subdomain": "wd5",
        },
        {
            "name": "ICF Next",
            "ats": "generic",
            "url": "https://careers.icf.com/us/en/search-results",
        },
        {
            "name": "Pearson",
            "ats": "generic",
            "url": "https://pearson.jobs/jobs/",
        },
        {
            "name": "Infosys",
            "ats": "generic",
            "url": "https://digitalcareers.infosys.com/infosys/global-careers?location=USA",
        },
        {
            "name": "Revance",
            "ats": "workday",
            "tenant": "revance",
            "board": "External",
            "wd_subdomain": "wd5",
        },
        {
            "name": "Apex Systems",
            "ats": "generic",
            "url": "https://www.apexsystems.com/careers/search-jobs",
        },
        {
            "name": "SweetRush",
            "ats": "generic",
            "url": "https://www.sweetrush.com/careers/",
        },
        {
            "name": "Salted",
            "ats": "generic",
            "url": "https://www.salted.com/careers",
        },
    ],
    "Weak": [
        {"name": "Typeface",    "ats": "greenhouse", "slug": "typeface"},
        {"name": "Stitch Fix",  "ats": "greenhouse", "slug": "stitchfix"},
        {"name": "Replicant",   "ats": "greenhouse", "slug": "replicant"},
        {"name": "Dropbox",     "ats": "greenhouse", "slug": "dropbox"},
        {"name": "SmartBug Media", "ats": "greenhouse", "slug": "smartbug-media"},
        {
            "name": "Shutterfly",
            "ats": "workday",
            "tenant": "shutterfly",
            "board": "External",
            "wd_subdomain": "wd5",
        },
    ],
    "Weak with Caveats": [
        {"name": "Known",           "ats": "greenhouse", "slug": "known"},
        {"name": "Pixalate",        "ats": "greenhouse", "slug": "pixalate"},
        {"name": "That's No Moon",  "ats": "greenhouse", "slug": "thatsnomoon"},
        {"name": "Baylor Genetics", "ats": "greenhouse", "slug": "baylorgenetics"},
        {
            "name": "Black & Black Creative",
            "ats": "generic",
            "url": "https://blackandblackcreative.com/careers",
        },
        {
            "name": "Hovercraft Studio",
            "ats": "generic",
            "url": "https://hovercraftstudio.com/careers",
        },
        {
            "name": "Tellos Creative",
            "ats": "generic",
            "url": "https://telloscreative.com/careers",
        },
        {
            "name": "Space Dinosaurs",
            "ats": "generic",
            "url": "https://spacedinosaursvfx.com/careers",
        },
        {
            "name": "Adly",
            "ats": "generic",
            "url": "https://adly.com/careers",
        },
    ],
}
